import { createSlice } from "@reduxjs/toolkit"; // Import createSlice function from Redux Toolkit

// Define the initial state of the user slice
const initialState = {
  token: null,
  name: null,
  email: null,
};

// Create a user slice using createSlice function
const userSlice = createSlice({
  name: "user", // Specify the name of the slice
  initialState, // Set the initial state
  reducers: {
    // Define reducer functions to update the user state
    setUser: (state, action) => { // Reducer to set user data
      state.token = action.payload.token; // Update token
      state.name = action.payload.name; // Update name
      state.email = action.payload.email; // Update email
    },
    clearUser: (state) => { // Reducer to clear user data
      state.token = null; // Clear token
      state.name = null; // Clear name
      state.email = null; // Clear email
    },
  },
});

// Extract action creators and reducer from the user slice
export const { setUser, clearUser } = userSlice.actions;

// Export the reducer function generated by createSlice
export default userSlice.reducer;
